services:
  fs0ciety-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fs0ciety-dashboard
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - PORT=3000
    ports:
      - "3333:3000"
    networks:
      - traefik_public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard-fs.rule=Host(`dashboard.internal.fs0ciety.org`)"
      - "traefik.http.routers.dashboard-fs.entrypoints=websecure"
      - "traefik.http.routers.dashboard-fs.tls=true"
      - "traefik.http.routers.dashboard-fs.tls.certresolver=cloudflare"
      - "traefik.http.services.dashboard-fs.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik_public"

networks:
  traefik_public:
    external: true
